# IMPORTS

In [2]:
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

# OPERAÇÕES

In [4]:
# Carregar dados
iris = load_iris()

# Visualizar o que há dentro do conjunto
print(f"""Nomes das features(medidas): {iris.feature_names}
Nomes das classes: {iris.target_names}""")

Nomes das features(medidas): ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Nomes das classes: ['setosa' 'versicolor' 'virginica']

In [5]:
# Transformando em DataFrame
df = pd.DataFrame(
    data = iris.data,
    columns = iris.feature_names
)

df['target'] = iris.target
df.head()

   sepal length (cm)  sepal width (cm)  ...  petal width (cm)  target
0                5.1               3.5  ...               0.2       0
1                4.9               3.0  ...               0.2       0
2                4.7               3.2  ...               0.2       0
3                4.6               3.1  ...               0.2       0
4                5.0               3.6  ...               0.2       0

[5 rows x 5 columns]

In [ ]:
#Separando os dados e a resposta

X = df.drop('target', axis=1)
y = df[['target']]
y

     target
0         0
1         0
2         0
3         0
4         0
..      ...
145       2
146       2
147       2
148       2
149       2

[150 rows x 1 columns]

In [12]:
# Divisão dos dados de treino e de teste

X_treino, X_test, y_treino, y_teste = train_test_split(
    X,
    y,
    test_size=0.2, 
    #random_state=42
)

print(f"""Total de amostras: {len(X)}
Amostras para treino: {len(X_treino)}
Amostra para teste: {len(X_test)}""")

Total de amostras: 150
Amostras para treino: 120
Amostra para teste: 30

In [16]:
# Criar e treinar o modelo

# Carregar modelo
model = KNeighborsClassifier(n_neighbors=3)

# Treinar modelo
model.fit(X_treino, y_treino)

# Fazer previsão
prev = model.predict(X_test)

# Analisar previsões
print(f'Previsões do modelo: {prev[:5]}')
print(f'Respostas reais: {y_teste[:5]}')

Previsões do modelo: [0 1 1 2 2]
Respostas reais:      target
18        0
75        1
56        1
102       2
117       2

C:\Users\Júlio César\AppData\Roaming\Python\Python313\site-packages\sklearn\neighbors\_classification.py:243: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

In [17]:
# Avaliar performance
acuracia = accuracy_score(y_teste, prev)

print(f'Acuracia do modelo: {acuracia:.2%}')

Acuracia do modelo: 100.00%